In [1]:
import numpy as np
import pandas as pd
np.random.seed(42)

# input features
cgpa = np.random.uniform(low=5.0, high=10.0, size=2500)
iq = np.random.normal(loc=100, scale=15, size=2500)
marks_12th = np.random.uniform(low=60, high=100, size=2500)
marks_10th = np.random.uniform(low=60, high=100, size=2500)

# generating probabilities
placement_prob = (cgpa/10 * 0.3 + iq/150 * 0.3 + marks_12th/100 * 0.2 + marks_10th/100 * 0.2) # the floating point values are the weightage/importance of each feature in the overall probability 
placed = np.random.binomial(1, placement_prob)

# Create DataFrame
student_data = pd.DataFrame({
    'CGPA': np.round(cgpa, 2),
    'IQ': np.round(iq),
    'Marks_12th': np.round(marks_12th, 2),
    'Marks_10th': np.round(marks_10th, 2),
    'Placed': placed
})

student_data.head()

,CGPA,IQ,Marks_12th,Marks_10th,Placed
0,6.87,108.0,89.67,81.37,0
1,9.75,110.0,87.01,92.95,1
2,8.66,108.0,68.24,64.13,0
3,7.99,101.0,74.10,97.72,1
4,5.78,97.0,65.04,91.80,1


In [2]:
# Shape of the dataset
student_data.shape

(2500, 5)

In [3]:
from pandas.core.series import Series
from pandas.core.frame import DataFrame

# Splitting the data
X: DataFrame = student_data.drop(columns=['Placed'])
y: Series = student_data['Placed']

In [4]:
import torch
from torch.utils.data import Dataset, DataLoader
from sklearn.preprocessing import StandardScaler

class CustomDataset(Dataset):
    def __init__(self: CustomDataset, features: np.ndarray, labels: np.ndarray) -> None:
        scaler = StandardScaler() # global pre-processings and feature engineering techniques
        self.features = scaler.fit_transform(X = features) # applies feature wise (axis = 0)
        self.labels = labels
        
        self.features = torch.tensor(self.features, device='cpu', requires_grad=False)
        self.labels = torch.tensor(self.labels, device='cpu', requires_grad=False)

    def __len__(self: CustomDataset) -> int:
        return self.features.shape[0]

    def __getitem__(self: CustomDataset, index):
        return self.features[index], self.labels[index] # the shape of these tensors gets changed based on the type of data you are working with (tabular → (batch_size, no_features), image → (batch_size, no_channels, height, width), text → (batch_size, no_tokens, embedding_dimension))

In [5]:
# dataset object
dataset = CustomDataset(
    features=np.array(X),
    labels=np.array(y)
)

# length of dataset
len(dataset)

2500

In [6]:
# Accessing a row
index = int(input("Enter your index → "))
features, labels = dataset[index]

print(f"Features at index {index}:", features)
print(f"Labels at index {index}:", labels)

Features at index 3: tensor([ 0.3409,  0.0895, -0.4832,  1.5762], dtype=torch.float64)
Labels at index 3: tensor(1)


In [ ]:
from torch.utils.data import BatchSampler, RandomSampler
sampler = RandomSampler(data_source=dataset)
batch_sampler = BatchSampler(sampler=sampler, batch_size=5, drop_last=False)

# Creating an object of dataset class → split the data into train and test then create a seperate dataloaders for each
dataloader = DataLoader(
    dataset=dataset,
    batch_size=5,
    # shuffle=True, # If True, the data is reshuffled at every epoch. False for data like `Time Series`
    sampler=sampler,
    batch_sampler=None,
    drop_last=False,
    pin_memory=True,
    num_workers=0 # if you mention more than zero workers then you will not be able to print the data
)

# Returning the generator
dataloader

##### sampler → 
A `sampler` defines the strategy to draw **individual samples** from the dataset. It yields one index at a time. It tells the DataLoader *which single item* to pick next <br>
`SequentialSampler`, `RandomSampler`, `WeightedRandomSampler` → Yields indices based on given probabilities (useful for imbalanced datasets).<br>
When you specify a `sampler` and a `batch_size`, the DataLoader will draw `batch_size` number of individual indices from the `sampler` and collate those individual items into a single batch.

##### batch_sampler →
A `batch_sampler` defines the strategy to draw a **whole batch of samples** at once. It yields a list (or batch) of indices at a time. It tells the DataLoader *which group of items* to pick next for a complete batch. <br>
<i>You use a `batch_sampler` when you need fine-grained control over which specific items end up in the same batch. For example, in natural language processing, you might want to group sentences of similar lengths into the same batch to minimize padding `custom function → collate_fn parameter`.</i><br>
If you specify a `batch_sampler`, you **cannot** specify `batch_size`, `shuffle`, `sampler`, or `drop_last`. The `batch_sampler` takes over the entire responsibility of batching and sampling.

In [9]:
for idx, (batch_features, batch_labels) in enumerate(dataloader): # At every iteration, dataloader return whatever you returned in __getitem__ function
    print(batch_features, batch_labels)
    if idx == 3:
        break
    print("_" * 50)

tensor([[ 0.9873, -0.5763, -0.1110, -0.0707],
        [-1.1584, -0.1103, -0.1258, -0.3052],
        [-1.6948,  1.0881,  1.0540, -1.4054],
        [-0.2644,  0.2226,  1.2674, -1.6664],
        [ 1.5994, -1.2421,  1.5979,  1.2774]], dtype=torch.float64) tensor([1, 1, 1, 1, 1])
__________________________________________________
tensor([[-0.2368, -1.7747,  1.0557,  0.3331],
        [ 1.5031, -0.2434,  1.4643,  1.0358],
        [ 1.0423,  0.7552,  1.5910,  0.8216],
        [ 0.5197,  2.2199,  0.1588, -1.6488],
        [-1.3647,  1.4210, -0.7434,  0.5588]], dtype=torch.float64) tensor([0, 1, 1, 1, 0])
__________________________________________________
tensor([[ 1.5306, -1.9078,  1.6630, -0.9734],
        [-1.5848,  0.0229, -0.8935, -1.0202],
        [ 0.0795, -2.8399,  1.2388,  0.8797],
        [-0.9315, -0.0437, -0.1388, -1.0449],
        [-0.5119, -0.9758,  1.3168, -1.1630]], dtype=torch.float64) tensor([1, 0, 1, 0, 1])
__________________________________________________
tensor([[ 0.4922,  

---

TODO: Implement it yourself and Improvements

In [32]:
documents: list[str] = [
    "short",
    "a medium length document",
    "tiny",
    "this is a considerably longer document that we will use for testing",
    "another medium one",
    "x",
    "a somewhat long document here",
    "medium length text",
    "very short",
    "the longest document in this small dataset should be placed with others of similar size",
]

class DocumentDataset(Dataset):
    def __init__(self, documents):
        self.documents = documents

    def __len__(self):
        return len(self.documents)

    def __getitem__(self, idx):
        # Return the document text and its length
        doc = self.documents[idx]
        return doc, len(doc)

dataset = DocumentDataset(documents)
lengths: list[int] = [len(doc) for doc in documents]
print(f"Lengths: {lengths}")

Lengths: [5, 24, 4, 67, 18, 1, 29, 18, 10, 87]


In [33]:
from typing import Any
from collections import defaultdict
from torch.utils.data import Sampler

import random

class BucketBatchSampler(Sampler):
    def __init__(self, lengths, batch_size, bucket_width=8, drop_last=False, shuffle=True, seed=0):
        self.batch_size = batch_size
        self.drop_last = drop_last
        self.shuffle = shuffle
        self.seed = seed
        self.epoch = 0

        groups: defaultdict[Any, list[Any]] = defaultdict(list) # creates a key automatically if not exists
        for idx, length in enumerate(lengths):
            groups[length // bucket_width].append(idx)
        self.groups: list[list[Any]] = list(groups.values())

    def set_epoch(self, epoch):
        """ We need a way for __iter__ to produce different random permutations on different calls, but still be deterministic if we rerun the same experiment """
        self.epoch = epoch

    def __iter__(self): # Sampler.__iter__ method is called once per epoch by the DataLoader
        rng = random.Random(self.seed + self.epoch)

        groups: list[list[int]] = [list(g) for g in self.groups]
        if self.shuffle:
            """ Shuffling batch sequence as well as records inside each batch """
            rng.shuffle(groups)
            for g in groups:
                rng.shuffle(g)

        for group in groups:
            for i in range(0, len(group), self.batch_size):
                batch: list[int] = group[i : i + self.batch_size]
                if self.drop_last and len(batch) < self.batch_size:
                    continue
                yield batch

    def __len__(self):
        if self.drop_last:
            # Only full batches are yielded: floor(n / b) per group.
            return sum(len(group) // self.batch_size for group in self.groups)
        # Every group yields ceil(n / b) batches, including the final partial one.
        return sum((len(group) + self.batch_size - 1) // self.batch_size
                for group in self.groups)

Problem: Hard boundaries. Length 15 and 16 land in different buckets if w = 16. This is arbitrary and wasteful; they are nearly identical.

In [34]:
import torch.utils.data.dataloader
batch_sampler = BucketBatchSampler(
    lengths, batch_size=4, drop_last=False
)

dataloader: torch.utils.data.dataloader.DataLoader[Any] = DataLoader(
    dataset=dataset,
    batch_sampler=batch_sampler,
    # TODO: What is the need of collete_fn parameter?
)

for idx, (batch_features, batch_labels) in enumerate(dataloader): # At every iteration, dataloader return whatever you returned in __getitem__ function
    print(batch_features, batch_labels)
    if idx != len(dataloader) - 1:
        print("_" * 50)

('very short',) tensor([10])
__________________________________________________
('this is a considerably longer document that we will use for testing',) tensor([67])
__________________________________________________
('a medium length document', 'a somewhat long document here') tensor([24, 29])
__________________________________________________
('short', 'x', 'tiny') tensor([5, 1, 4])
__________________________________________________
('the longest document in this small dataset should be placed with others of similar size',) tensor([87])
__________________________________________________
('another medium one', 'medium length text') tensor([18, 18])
