In [121]:
# Importing torch
import torch
print(torch.__version__)

2.9.1+cu126


In [122]:
# GPU avaliability
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU is available!
Using GPU: NVIDIA GeForce MX350


#### Tensor Creation Methods

In [123]:
# This method will assign a memory to create a tensor of provided shape and return the existing numbers at that location
a = torch.empty(2, 3)
a

tensor([[10.0000,  0.5739,  0.2666],
        [ 0.6274,  0.2696,  0.4414]])

In [124]:
# Check type
type(a)

torch.Tensor

In [125]:
# Using zeros
torch.zeros(size = [2, 3], dtype = torch.float32)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [126]:
# using ones
torch.ones(size = [2, 3])

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [127]:
# using rand
torch.rand(size = [2, 3])

tensor([[0.3813, 0.7860, 0.1115],
        [0.2477, 0.6524, 0.6057]])

In [128]:
# manual_seed - for regenerating the same array
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [129]:
# using tensor
torch.tensor(
    data = [[1,2,3],[4,5,6]],
    dtype = torch.float32,
    requires_grad = False,
    pin_memory = True # The tensor will directly loded into pin-memory and not pager-memory, for faster loading. pin_memory=True is primarily a GPU optimization tool that prepares CPU data for faster transfer to the GPU.
)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

*When you create a regular tensor, your operating system can move its data between RAM and disk (virtual memory). This is efficient for general use but unpredictable for transfers to a GPU.*

*Setting pin_memory=True tells PyTorch to allocate the tensor in page-locked (pinned) memory. This guarantees the data stays in RAM, enabling the GPU's Direct Memory Access (DMA) to perform a direct and fast transfer. Without it, the system must create a temporary pinned copy first, which is slower.*

*Pinned memory (page-locked memory) is a feature of CPU memory that allows for faster, asynchronous data transfers to the GPU.*
*You can only pin tensors that are currently on the CPU.*
*Once a tensor is already on the GPU (device='cuda'), it cannot be "pinned" because it is no longer in system RAM.*

In [130]:
# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,10))

# using eye - Identity Matrix tensor
print("using eye ->", torch.eye(5))

# using full - torch.ones(size = (m, n)) * constant( = 5)
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


---

#### Tensor Shape

In [131]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [132]:
x.shape

torch.Size([2, 3])

In [133]:
# Create an uninitialized tensor with the same shape as the input tensor
torch.empty_like(
    input=x,
    memory_format=torch.preserve_format,
    dtype=torch.float32,
    layout=x.layout,
    device='cuda',
    pin_memory=False,
    requires_grad=False
)

tensor([[0., 0., 0.],
        [0., 0., 0.]], device='cuda:0')

In [134]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [135]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [136]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])

*`_like()` methods creates new tensor having the same shape as of input tensor.*

---

#### Tensor DataTypes

In [137]:
# find data type
x.dtype

torch.int64

In [138]:
# assign data type
torch.tensor([1.0, 2.0, 3.0], dtype = torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [139]:
torch.tensor([1, 2, 3], dtype = torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [140]:
# using to() - Type Conversion - Generally used to transfer a tensor from cpu to gpu
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


---

#### Mathematical Operations

In [141]:
x = torch.rand(2,2)
x

tensor([[0.8694, 0.5677],
        [0.7411, 0.4294]])

In [142]:
# Scalar Operations

# addition
print(x + 2, end = "\n\n")

# substraction
print(x - 2, end = "\n\n")

# multiplication
print(x * 3, end = "\n\n")

# division
print(x / 3, end = "\n\n")

# int division
print((x * 100) // 3, end = "\n\n")

# mod
print(((x * 100) // 3) % 2, end = "\n\n")

# power
print(x ** 2)

tensor([[2.8694, 2.5677],
        [2.7411, 2.4294]])

tensor([[-1.1306, -1.4323],
        [-1.2589, -1.5706]])

tensor([[2.6082, 1.7031],
        [2.2233, 1.2882]])

tensor([[0.2898, 0.1892],
        [0.2470, 0.1431]])

tensor([[28., 18.],
        [24., 14.]])

tensor([[0., 0.],
        [0., 0.]])

tensor([[0.7559, 0.3223],
        [0.5492, 0.1844]])


In [143]:
# Element wise operation
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.8854, 0.5739, 0.2666],
        [0.6274, 0.2696, 0.4414]])
tensor([[0.2969, 0.8317, 0.1053],
        [0.2695, 0.3588, 0.1994]])


In [144]:
# Shape must be same or able to broadcast

# add
print(a + b, end="\n\n")

# sub
print(a - b, end="\n\n")

# multiply
print(a * b, end="\n\n")

# division
print(a / b, end="\n\n")

# power
print(a ** b, end="\n\n")

# mod
print(a % b)

tensor([[1.1824, 1.4056, 0.3719],
        [0.8969, 0.6284, 0.6407]])

tensor([[ 0.5885, -0.2578,  0.1613],
        [ 0.3580, -0.0892,  0.2420]])

tensor([[0.2629, 0.4773, 0.0281],
        [0.1691, 0.0967, 0.0880]])

tensor([[2.9821, 0.6900, 2.5313],
        [2.3282, 0.7515, 2.2139]])

tensor([[0.9645, 0.6301, 0.8700],
        [0.8820, 0.6248, 0.8495]])

tensor([[0.2916, 0.5739, 0.0560],
        [0.0885, 0.2696, 0.0426]])


In [145]:
c = torch.tensor([1, -2, 3, -4])
c

tensor([ 1, -2,  3, -4])

In [146]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [147]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [148]:
# Inplace operations
print(torch.abs_(c))
print(c)

print(torch.neg_(c))
print(c)

tensor([1, 2, 3, 4])
tensor([1, 2, 3, 4])
tensor([-1, -2, -3, -4])
tensor([-1, -2, -3, -4])


In [149]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])
d

tensor([1.9000, 2.3000, 3.7000, 4.4000])

In [150]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [151]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [152]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [153]:
# clamp | clip - Clipping in a certing range
torch.clip(d, min = -1, max = 1)
torch.clamp(d, min = -1, max = 1)

tensor([1., 1., 1., 1.])

In [154]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[7., 9., 2.],
        [0., 5., 9.]])

In [155]:
# Aggregate operation

# sum
torch.sum(e)

# sum along columns
print(torch.sum(e, dim = 0, keepdim=False)) # same as `axis` parameter in numpy

# sum along rows
print(torch.sum(e, dim = 1, keepdim=True))

tensor([ 7., 14., 11.])
tensor([[18.],
        [14.]])


In [156]:
# mean
torch.mean(e)

# mean along col
torch.mean(e, dim=0)

tensor([3.5000, 7.0000, 5.5000])

In [157]:
# median
torch.median(e)

tensor(5.)

In [158]:
# max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [159]:
# product
torch.prod(e)

tensor(0.)

In [160]:
# standard deviation
torch.std(e)

tensor(3.7238)

In [161]:
# variance
torch.var(e)

tensor(13.8667)

In [162]:
# argmax
torch.argmax(e)

tensor(1)

In [163]:
# argmin
torch.argmin(e)

tensor(3)

---

#### Matrix operations

In [164]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[3, 4, 9],
        [6, 2, 0]])
tensor([[6, 2],
        [7, 9],
        [7, 3]])


In [165]:
# matrix multiplcation - dot product
torch.matmul(f, g)

tensor([[109,  69],
        [ 50,  30]])

In [166]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product - only works with 1D Tensors
torch.dot(vector1, vector2)

tensor(11)

In [167]:
# transpose
torch.transpose(f, 0, 1)

tensor([[3, 6],
        [4, 2],
        [9, 0]])

In [168]:
torch.transpose(f, dim0 = 1, dim1 = 0)

tensor([[3, 6],
        [4, 2],
        [9, 0]])

In [169]:
temp = torch.tensor([
    [[1], [2]],
    [[1], [3]],
    [[1], [4]],
])

print(temp.shape)
torch.transpose(temp, dim0=0, dim1=1).shape # Check the dimentions and its index correctly

torch.Size([3, 2, 1])


torch.Size([2, 3, 1])

In [170]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[3., 4., 3.],
        [7., 0., 9.],
        [0., 9., 6.]])

In [171]:
# determinant
torch.det(h)

tensor(-222.)

In [172]:
# inverse
torch.inverse(h)

tensor([[ 0.3649, -0.0135, -0.1622],
        [ 0.1892, -0.0811,  0.0270],
        [-0.2838,  0.1216,  0.1261]])

---

#### Comparison operations

In [173]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[9, 5, 4],
        [8, 8, 6]])
tensor([[0, 0, 0],
        [0, 1, 3]])


In [174]:
# Element wise comparison - Shape must be same

# greater than
print(i > j)

# less than
print(i < j)

# equal to
print(i == j)

# not equal to
print(i != j)

tensor([[True, True, True],
        [True, True, True]])
tensor([[False, False, False],
        [False, False, False]])
tensor([[False, False, False],
        [False, False, False]])
tensor([[True, True, True],
        [True, True, True]])


---

#### Special functions

In [175]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[0., 1., 1.],
        [7., 9., 4.]])

In [176]:
# log - base e
torch.log(input = k)

# log - base 10
torch.log10(input = k)

tensor([[  -inf, 0.0000, 0.0000],
        [0.8451, 0.9542, 0.6021]])

In [177]:
# Checking the size of the elements in the tensor
tensor = torch.log10(input = k)
tensor.element_size()  # size in bytes of a single element

4

In [178]:
# exp
torch.exp(k)

tensor([[1.0000e+00, 2.7183e+00, 2.7183e+00],
        [1.0966e+03, 8.1031e+03, 5.4598e+01]])

In [179]:
# sqrt
torch.sqrt(k)

tensor([[0.0000, 1.0000, 1.0000],
        [2.6458, 3.0000, 2.0000]])

In [180]:
# sigmoid
torch.sigmoid(k)

tensor([[0.5000, 0.7311, 0.7311],
        [0.9991, 0.9999, 0.9820]])

In [181]:
# softmax
torch.softmax(k, dim = 1)

tensor([[0.1554, 0.4223, 0.4223],
        [0.1185, 0.8756, 0.0059]])

In [182]:
# relu
torch.relu(k)

tensor([[0., 1., 1.],
        [7., 9., 4.]])

---

#### Inplace Operations

In [183]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.0874, 0.0041, 0.1088],
        [0.1637, 0.7025, 0.6790]])
tensor([[0.9155, 0.2418, 0.1591],
        [0.7653, 0.2979, 0.8035]])


In [184]:
# _ methods
m.add_(n) # It returns the new matrix

tensor([[1.0028, 0.2458, 0.2680],
        [0.9289, 1.0004, 1.4825]])

In [185]:
m # Updated

tensor([[1.0028, 0.2458, 0.2680],
        [0.9289, 1.0004, 1.4825]])

In [186]:
n

tensor([[0.9155, 0.2418, 0.1591],
        [0.7653, 0.2979, 0.8035]])

In [187]:
torch.relu(m)

tensor([[1.0028, 0.2458, 0.2680],
        [0.9289, 1.0004, 1.4825]])

In [188]:
m.relu_()

tensor([[1.0028, 0.2458, 0.2680],
        [0.9289, 1.0004, 1.4825]])

In [189]:
m

tensor([[1.0028, 0.2458, 0.2680],
        [0.9289, 1.0004, 1.4825]])

---

#### Copying a Tensor

In [190]:
b = a.clone()

print(a, b, sep = '\n')

tensor([[0.8854, 0.5739, 0.2666],
        [0.6274, 0.2696, 0.4414]])
tensor([[0.8854, 0.5739, 0.2666],
        [0.6274, 0.2696, 0.4414]])


In [191]:
a[0][0] = 10

print(a, b, sep = '\n')

tensor([[10.0000,  0.5739,  0.2666],
        [ 0.6274,  0.2696,  0.4414]])
tensor([[0.8854, 0.5739, 0.2666],
        [0.6274, 0.2696, 0.4414]])


In [192]:
id(a)

2036432271264

In [193]:
id(b)

2036432267824