In [1]:
import torch
print(torch.__version__)

2.8.0+cu126


In [2]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU is available!
Using GPU: NVIDIA GeForce MX350


## **<u>Tensor Creation Methods</u>**

In [3]:
# This method will assign a memory to create a tensor of provided shape and return the existing numbers at that location
a = torch.empty(2, 3)
a

tensor([[-2.0157e+00,  7.7352e-43,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [4]:
# Check type
type(a)

torch.Tensor

In [5]:
# Using zeros
torch.zeros(size = [2, 3], dtype = torch.float32)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
# using ones
torch.ones(size = [2, 3])

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [23]:
# using rand
torch.rand(size = [2, 3])

tensor([[0.2666, 0.6274, 0.2696],
        [0.4414, 0.2969, 0.8317]])

In [20]:
# manual_seed - for regenerating the same array
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [24]:
# using tensor
torch.tensor(
    data = [[1,2,3],[4,5,6]],
    dtype = torch.float32,
    requires_grad = False,
    pin_memory = True # The tensor will directly loded into pin-memory and not pager-memory, for faster loading
)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [25]:
# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,10))

# using eye - Identity Matrix tensor
print("using eye ->", torch.eye(5))

# using full - torch.ones(size = (m, n)) * constant( = 5)
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


---

## **<u>Tensor Shape</u>**

In [26]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [27]:
x.shape

torch.Size([2, 3])

In [31]:
torch.empty_like(x)
# This method will copy the shape of the tensor passed as an argument

tensor([[4615689221071321316, 4651718018103334230, 4671734013112731420],
        [4687746815133016974,          1092616192,                   0]])

In [32]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [33]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [34]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.1053, 0.2695, 0.3588],
        [0.1994, 0.5472, 0.0062]])

---

## **<u>Tensor DataTypes</u>**

In [35]:
# find data type
x.dtype

torch.int64

In [36]:
# assign data type
torch.tensor([1.0, 2.0, 3.0], dtype = torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [37]:
torch.tensor([1, 2, 3], dtype = torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [39]:
# using to() - Type Conversion - Generally used to transfer a tensor from cpu to gpu
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


---

## **<u>Mathematical Operations</u>**

In [40]:
x = torch.rand(2,2)
x

tensor([[0.9516, 0.0753],
        [0.8860, 0.5832]])

In [41]:
# Scalar Operations

# addition
x + 2

# substraction
x - 2

# multiplication
x * 3

# division
x / 3

# int division
(x * 100) // 3

# mod
((x * 100) // 3) % 2

# power
x ** 2

tensor([[0.9055, 0.0057],
        [0.7850, 0.3401]])

In [42]:
# Element wise operation
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.3376, 0.8090, 0.5779],
        [0.9040, 0.5547, 0.3423]])
tensor([[0.6343, 0.3644, 0.7104],
        [0.9464, 0.7890, 0.2814]])


In [ ]:
# Shape must be same or able to broadcast

# add
a + b

# sub
a - b

# multiply
a * b

# division
a / b

# power
a ** b

# mod
a % b

tensor([[0.3376, 0.0802, 0.5779],
        [0.9040, 0.5547, 0.0609]])

In [45]:
c = torch.tensor([1, -2, 3, -4])
c

tensor([ 1, -2,  3, -4])

In [46]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [47]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [48]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])
d

tensor([1.9000, 2.3000, 3.7000, 4.4000])

In [49]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [50]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [51]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [54]:
# clamp | clip - Clipping in a certing range
torch.clip(d, min = -1, max = 1)
torch.clamp(d, min = -1, max = 1)

tensor([1., 1., 1., 1.])

In [55]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[9., 6., 9.],
        [5., 4., 8.]])

In [56]:
# Reduction operation

# sum
torch.sum(e)

# sum along columns
torch.sum(e, dim = 0) # same as `axis` parameter in numpy

# sum along rows
torch.sum(e, dim = 1)

tensor([24., 17.])

In [57]:
# mean
torch.mean(e)

# mean along col
torch.mean(e, dim=0)

tensor([7.0000, 5.0000, 8.5000])

In [58]:
# median
torch.median(e)

tensor(6.)

In [59]:
# max and min
torch.max(e)
torch.min(e)

tensor(4.)

In [60]:
# product
torch.prod(e)

tensor(77760.)

In [61]:
# standard deviation
torch.std(e)

tensor(2.1370)

In [62]:
# variance
torch.var(e)

tensor(4.5667)

In [63]:
# argmax
torch.argmax(e)

tensor(0)

In [64]:
# argmin
torch.argmin(e)

tensor(4)

---

## **<u>Matrix operations</u>**

In [65]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[8, 6, 0],
        [0, 0, 0]])
tensor([[1, 3],
        [0, 1],
        [1, 7]])


In [66]:
# matrix multiplcation - dot product
torch.matmul(f, g)

tensor([[ 8, 30],
        [ 0,  0]])

In [67]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product - only works with 1D Tensors
torch.dot(vector1, vector2)

tensor(11)

In [68]:
# transpose
torch.transpose(f, 0, 1)

tensor([[8, 0],
        [6, 0],
        [0, 0]])

In [73]:
torch.transpose(f, dim0 = 1, dim1 = 0)

tensor([[8, 0],
        [6, 0],
        [0, 0]])

In [74]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[9., 4., 3.],
        [8., 9., 3.],
        [7., 8., 1.]])

In [75]:
# determinant
torch.det(h)

tensor(-80.)

In [76]:
# inverse
torch.inverse(h)

tensor([[ 0.1875, -0.2500,  0.1875],
        [-0.1625,  0.1500,  0.0375],
        [-0.0125,  0.5500, -0.6125]])

---

## **<u>Comparison operations</u>**

In [77]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[4, 1, 6],
        [3, 2, 0]])
tensor([[9, 8, 5],
        [3, 7, 7]])


In [78]:
# Element wise comparison - Shape must be same

# greater than
i > j

# less than
i < j

# equal to
i == j

# not equal to
i != j

tensor([[ True,  True,  True],
        [False,  True,  True]])

---

## **<u>Special functions</u>**

In [79]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[5., 9., 1.],
        [5., 1., 9.]])

In [80]:
# log - base e
torch.log(input = k)

tensor([[1.6094, 2.1972, 0.0000],
        [1.6094, 0.0000, 2.1972]])

In [81]:
# exp
torch.exp(k)

tensor([[1.4841e+02, 8.1031e+03, 2.7183e+00],
        [1.4841e+02, 2.7183e+00, 8.1031e+03]])

In [82]:
# sqrt
torch.sqrt(k)

tensor([[2.2361, 3.0000, 1.0000],
        [2.2361, 1.0000, 3.0000]])

In [83]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9933, 0.9999, 0.7311],
        [0.9933, 0.7311, 0.9999]])

In [84]:
# softmax
torch.softmax(k, dim = 1)

tensor([[1.7980e-02, 9.8169e-01, 3.2932e-04],
        [1.7980e-02, 3.2932e-04, 9.8169e-01]])

In [85]:
# relu
torch.relu(k)

tensor([[5., 9., 1.],
        [5., 1., 9.]])

---

## **<u>Inplace Operations</u>**

In [86]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.3227, 0.0162, 0.2137],
        [0.6249, 0.4340, 0.1371]])
tensor([[0.5117, 0.1585, 0.0758],
        [0.2247, 0.0624, 0.1816]])


In [ ]:
# _ methods
m.add_(n) # It returns the new matrix

tensor([[0.8345, 0.1747, 0.2895],
        [0.8496, 0.4964, 0.3187]])

In [88]:
m # Updated

tensor([[0.8345, 0.1747, 0.2895],
        [0.8496, 0.4964, 0.3187]])

In [89]:
n

tensor([[0.5117, 0.1585, 0.0758],
        [0.2247, 0.0624, 0.1816]])

In [90]:
torch.relu(m)

tensor([[0.8345, 0.1747, 0.2895],
        [0.8496, 0.4964, 0.3187]])

In [91]:
m.relu_()

tensor([[0.8345, 0.1747, 0.2895],
        [0.8496, 0.4964, 0.3187]])

In [92]:
m

tensor([[0.8345, 0.1747, 0.2895],
        [0.8496, 0.4964, 0.3187]])

---

## **<u>Copying a Tensor</u>**

In [93]:
b = a.clone()

In [94]:
a

tensor([[0.3376, 0.8090, 0.5779],
        [0.9040, 0.5547, 0.3423]])

In [95]:
b

tensor([[0.3376, 0.8090, 0.5779],
        [0.9040, 0.5547, 0.3423]])

In [96]:
a[0][0] = 10

In [97]:
a

tensor([[10.0000,  0.8090,  0.5779],
        [ 0.9040,  0.5547,  0.3423]])

In [98]:
b

tensor([[0.3376, 0.8090, 0.5779],
        [0.9040, 0.5547, 0.3423]])

In [99]:
id(a)

1618468298640

In [100]:
id(b)

1618469085232